using System;
using System.Collections.Generic;

namespace DemoApp.Charts;

/// <summary>
/// The demo's words: its pages' names, the captions it gives its series, axes and gauges, its buttons and its status lines, on
/// keys of the demo's own prefix, in English and in a second language that also carries every framework, code field and chart
/// word the demo registers.
/// </summary>
internal static class ChartsDemoWords
{
    /// <summary>What every key of the demo starts with; every other string is content (<c>KeyPrefixes</c>).</summary>
    public const string KeyPrefix = "charts.";

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        ["charts.eu-west"] = "Europe West",
        ["charts.eu-central"] = "Europe Central",
        ["charts.us-east"] = "US East",
        ["charts.asia-south"] = "Asia South",
        ["charts.requests"] = "Requests",
        ["charts.requests-a-minute"] = "Requests a minute",
        ["charts.cpu"] = "CPU",
        ["charts.average-cpu"] = "Average CPU, %",
        ["charts.memory"] = "Memory",
        ["charts.revenue"] = "Revenue, €k",
        ["charts.revenue-a-month"] = "€68.9k a month",
        ["charts.servers"] = "Servers",
        ["charts.quarter"] = "Quarter",
        ["charts.time"] = "Time",
        ["charts.percent"] = "Percent",
        ["charts.hour"] = "Hour",
        ["charts.disk-eu-west"] = "Disk used in Europe West",
        ["charts.outside-asia-south"] = "Outside Asia South, no sensor yet",
        ["charts.revenue-a-year"] = "€827k a year",
        ["charts.processor-at"] = "Processor at {time}",
        ["charts.unit.rising"] = "% and rising",
        ["charts.unit.falling"] = "% and falling",
        ["charts.spark.cpu"] = "CPU of api-eu-west-1, the last forty readings",
        ["charts.spark.revenue"] = "Revenue in Europe West, by quarter",

        ["charts.button.take-reading"] = "Take a reading",
        ["charts.button.change-last"] = "Change the last one",
        ["charts.button.last-ten-minutes"] = "Show the last ten minutes",
        ["charts.button.a-month"] = "A month",
        ["charts.button.a-year"] = "A year",
        ["charts.status.live"] = "The live chart holds forty readings. Take one and the line follows it.",
        ["charts.status.reading"] = "Reading at {time}: CPU {cpu}%, memory {memory}%.",
        ["charts.status.showing-all"] = "Showing all {total} readings.",
        ["charts.status.showing"] = "Showing {from} to {to}: {inside} of {total} readings.",
        ["charts.status.last-ten-minutes"] = "The last ten minutes, set by the controller rather than by the wheel.",
        ["charts.status.point"] = "{series} at {time}: CPU {cpu}%, memory {memory}%.",
        ["charts.status.point-unknown"] = "A point of {series} was clicked: {point}.",
        ["charts.status.changed"] = "The reading at {time} now says CPU {cpu}%.",
        ["charts.status.bar-hint"] = "Press a bar for its value.",
        ["charts.status.bar"] = "A bar was pressed: {series} of {point}.",

        ["charts.page.lines"] = "Lines",
        ["charts.page.lines.description"] = "SVG the server writes and the browser keeps: a point is an item of a keyed collection, so a reading that arrives moves one point.",
        ["charts.page.areas-and-bars"] = "Areas and bars",
        ["charts.page.areas-and-bars.description"] = "The line chart with its ground filled, and the chart that gives every x a band: bands, bars, a stack, and bars on their side.",
        ["charts.page.pie-and-scatter"] = "Pie and scatter",
        ["charts.page.pie-and-scatter.description"] = "The two charts without a line: a turn shared out between one series' points, and a cloud of points sized by a third value.",
        ["charts.page.radar"] = "Radar",
        ["charts.page.radar.description"] = "Series as shapes over spokes: a row names a spoke, and each series' values along them close into an outline to read against the others.",
        ["charts.page.sparks-and-gauges"] = "Sparks and gauges",
        ["charts.page.sparks-and-gauges.description"] = "The charts that stand in a cell or the corner of a tile; take a reading and watch the load's spark and its arc follow it.",
        ["charts.code"] = "Code",
        ["charts.copy"] = "Copy"
    };

    // The demo's second language, whole: every word of its own and every framework, code field (the source flyout) and chart word it
    // registers, so the missing-word report names only a real gap (DemoWordsCoverageTests). The framework ships English only; an
    // application brings every other language.
    private static readonly Dictionary<string, string> Chinese = new(StringComparer.Ordinal)
    {
        ["ui.picker.today"] = "今天",
        ["ui.picker.now"] = "现在",
        ["ui.picker.clear"] = "清除",
        ["ui.picker.done"] = "完成",
        ["ui.picker.previous"] = "上一个",
        ["ui.picker.next"] = "下一个",
        ["ui.picker.hours"] = "小时",
        ["ui.picker.minutes"] = "分钟",
        ["ui.picker.seconds"] = "秒",
        ["ui.picker.meridiem"] = "上午/下午",
        ["ui.picker.start"] = "开始",
        ["ui.picker.end"] = "结束",
        ["ui.picker.open"] = "打开选择器",
        ["ui.notification.close"] = "关闭",
        ["ui.tabs.more"] = "更多标签页",
        ["ui.commandbar.more"] = "更多命令",
        ["ui.tab.close"] = "关闭",
        ["ui.tab.rename"] = "重命名",
        ["ui.tab.pin"] = "固定",
        ["ui.tab.unpin"] = "取消固定",
        ["ui.tab.delete"] = "删除",
        ["ui.select.clear"] = "清除选择",
        ["ui.select.placeholder"] = "请选择…",
        ["ui.select.remove"] = "移除 {label}",
        ["ui.input.clear"] = "清除",
        ["ui.breadcrumbs.label"] = "面包屑导航",
        ["ui.file.uploading"] = "正在上传… {percent}%",
        ["ui.file.count"] = "{count} 个文件",
        ["ui.file.failed"] = "上传失败。",
        ["ui.file.oversized"] = "文件太大。",
        ["ui.file.choose"] = "选择文件",
        ["ui.color.picker"] = "取色器",
        ["ui.color.palette"] = "调色板",
        ["ui.color.hex"] = "十六进制",
        ["ui.color.red"] = "R",
        ["ui.color.green"] = "G",
        ["ui.color.blue"] = "B",
        ["ui.color.factor"] = "系数",
        ["ui.color.opacity"] = "不透明度",
        ["ui.color.choose"] = "选择颜色",
        ["ui.splitter.label"] = "调整大小",
        ["ui.split.more"] = "更多操作",
        ["ui.image.choose"] = "选择图片",
        ["ui.image.change"] = "更换图片",
        ["ui.image.remove"] = "移除图片",
        ["ui.row.edit"] = "编辑",
        ["ui.row.save"] = "保存",
        ["ui.row.cancel"] = "取消",
        ["ui.table.resize"] = "调整列宽",
        ["ui.tree.toggle"] = "展开或折叠",
        ["ui.tree.loading"] = "正在加载…",
        ["ui.items.empty"] = "没有可显示的内容。",
        ["ui.collapse.toggle"] = "展开或折叠",
        ["ui.side.open"] = "打开侧栏",
        ["ui.menu.search"] = "搜索",
        ["ui.theme.switch"] = "切换主题",
        ["ui.language.switch"] = "切换语言，{language}",
        ["ui.notfound.title"] = "404",
        ["ui.notfound.description"] = "你要找的页面不存在。",
        ["ui.notfound.page"] = "页面不存在",
        ["ui.error.title"] = "出了点问题",
        ["ui.error.message"] = "出了点问题，请重试。",
        ["ui.command.refused"] = "你无权执行此操作。",
        ["ui.command.failed"] = "出了点问题，请重试。",
        ["ui.value.format"] = "值的格式不对。",
        ["ui.connection.lost"] = "与服务器的连接已断开。请重新加载页面以继续。",
        ["ui.connection.reload"] = "重新加载",

        ["ui.color.name.iron-fog"] = "铁雾",
        ["ui.color.name.silver-night"] = "银夜",
        ["ui.color.name.bronze-dusk"] = "青铜暮色",
        ["ui.color.name.stellar-red"] = "星红",
        ["ui.color.name.nebula-rose"] = "星云玫瑰",
        ["ui.color.name.lunar-pink"] = "月光粉",
        ["ui.color.name.solar-amber"] = "太阳琥珀",
        ["ui.color.name.nebula-gold"] = "星云金",
        ["ui.color.name.lunar-yellow"] = "月光黄",
        ["ui.color.name.eclipse-olive"] = "日食橄榄",
        ["ui.color.name.nebula-lime"] = "星云青柠",
        ["ui.color.name.lunar-sage"] = "月光鼠尾草",
        ["ui.color.name.aurora-green"] = "极光绿",
        ["ui.color.name.nebula-mint"] = "星云薄荷",
        ["ui.color.name.lunar-fern"] = "月光蕨",
        ["ui.color.name.astral-teal"] = "星青",
        ["ui.color.name.nebula-cyan"] = "星云青",
        ["ui.color.name.lunar-moss"] = "月光苔",
        ["ui.color.name.quantum-blue"] = "量子蓝",
        ["ui.color.name.nebula-aqua"] = "星云水蓝",
        ["ui.color.name.lunar-azure"] = "月光天蓝",
        ["ui.color.name.nova-purple"] = "新星紫",
        ["ui.color.name.nebula-violet"] = "星云紫罗兰",
        ["ui.color.name.lunar-lavender"] = "月光薰衣草",
        ["ui.color.name.comet"] = "彗星",
        ["ui.color.name.flare"] = "耀斑",
        ["ui.color.name.ember"] = "余烬",
        ["ui.color.name.photon"] = "光子",
        ["ui.color.name.vortex"] = "漩涡",
        ["ui.color.name.halo"] = "光环",

        ["ui.code.find"] = "查找",
        ["ui.code.replace"] = "替换",
        ["ui.code.replace-one"] = "替换",
        ["ui.code.replace-all"] = "全部替换",
        ["ui.code.toggle-replace"] = "切换替换",
        ["ui.code.previous"] = "上一个匹配",
        ["ui.code.next"] = "下一个匹配",
        ["ui.code.close"] = "关闭",
        ["ui.code.match-case"] = "区分大小写",
        ["ui.code.whole-word"] = "全字匹配",
        ["ui.code.regex"] = "正则表达式",
        ["ui.code.indentation"] = "缩进",
        ["ui.code.encoding"] = "编码",
        ["ui.code.line-ending"] = "行尾",
        ["ui.code.language"] = "语言",
        ["ui.code.plain-text"] = "纯文本",
        ["ui.code.utf8-bom"] = "UTF-8（带 BOM）",
        ["ui.code.matches"] = "第 {current} 个，共 {total} 个",
        ["ui.code.no-matches"] = "无匹配",
        ["ui.code.invalid-pattern"] = "无效的模式",
        ["ui.code.position"] = "行 {line}，列 {column}",
        ["ui.code.suggestions"] = "建议",
        ["ui.code.spaces-1"] = "1 个空格",
        ["ui.code.spaces-2"] = "2 个空格",
        ["ui.code.spaces-3"] = "3 个空格",
        ["ui.code.spaces-4"] = "4 个空格",
        ["ui.code.spaces-5"] = "5 个空格",
        ["ui.code.spaces-6"] = "6 个空格",
        ["ui.code.spaces-7"] = "7 个空格",
        ["ui.code.spaces-8"] = "8 个空格",

        ["ui.chart.label"] = "图表",
        ["ui.chart.empty"] = "没有数据",
        ["ui.chart.no-reading"] = "无读数",
        ["ui.chart.point"] = "{series} — {x}：{y}",
        ["ui.chart.sector"] = "{label} — {value}",
        ["ui.chart.reading"] = "{series}：{value}",
        ["ui.chart.list"] = "{list}、{next}",

        ["charts.eu-west"] = "西欧",
        ["charts.eu-central"] = "中欧",
        ["charts.us-east"] = "美国东部",
        ["charts.asia-south"] = "南亚",
        ["charts.requests"] = "请求",
        ["charts.requests-a-minute"] = "每分钟请求数",
        ["charts.cpu"] = "处理器",
        ["charts.average-cpu"] = "平均处理器占用，%",
        ["charts.memory"] = "内存",
        ["charts.revenue"] = "收入（千欧元）",
        ["charts.revenue-a-month"] = "每月 6.89 万欧元",
        ["charts.servers"] = "服务器",
        ["charts.quarter"] = "季度",
        ["charts.time"] = "时间",
        ["charts.percent"] = "百分比",
        ["charts.hour"] = "小时",
        ["charts.disk-eu-west"] = "西欧磁盘用量",
        ["charts.outside-asia-south"] = "南亚室外，尚无传感器",
        ["charts.revenue-a-year"] = "每年 82.7 万欧元",
        ["charts.processor-at"] = "{time} 的处理器",
        ["charts.unit.rising"] = "%，上升中",
        ["charts.unit.falling"] = "%，下降中",
        ["charts.spark.cpu"] = "api-eu-west-1 的处理器占用，最近四十个读数",
        ["charts.spark.revenue"] = "西欧收入，按季度",

        ["charts.button.take-reading"] = "读取一次",
        ["charts.button.change-last"] = "修改最后一个",
        ["charts.button.last-ten-minutes"] = "显示最近十分钟",
        ["charts.button.a-month"] = "每月",
        ["charts.button.a-year"] = "每年",
        ["charts.status.live"] = "实时图表保留四十个读数。读取一次，折线随之延伸。",
        ["charts.status.reading"] = "{time} 的读数：处理器 {cpu}%，内存 {memory}%。",
        ["charts.status.showing-all"] = "显示全部 {total} 个读数。",
        ["charts.status.showing"] = "显示 {from} 至 {to}：{total} 个读数中的 {inside} 个。",
        ["charts.status.last-ten-minutes"] = "最近十分钟，由控制器而非滚轮设定。",
        ["charts.status.point"] = "{time} 的{series}：处理器 {cpu}%，内存 {memory}%。",
        ["charts.status.point-unknown"] = "点击了{series}的一个点：{point}。",
        ["charts.status.changed"] = "{time} 的读数现在为处理器 {cpu}%。",
        ["charts.status.bar-hint"] = "按下柱形查看其数值。",
        ["charts.status.bar"] = "按下了一个柱形：{point} 的{series}。",

        ["charts.page.lines"] = "折线图",
        ["charts.page.lines.description"] = "由服务器写出、浏览器保留的 SVG：每个点都是带键集合中的一项，因此新到的一个读数只移动一个点。",
        ["charts.page.areas-and-bars"] = "面积图与柱状图",
        ["charts.page.areas-and-bars.description"] = "填满下方区域的折线图，以及为每个 x 分出一个区间的图表：面积带、柱形、堆叠，以及横放的柱形。",
        ["charts.page.pie-and-scatter"] = "饼图与散点图",
        ["charts.page.pie-and-scatter.description"] = "两种没有连线的图表：把一整圈分给一个系列的各个点，以及按第三个值确定大小的点云。",
        ["charts.page.radar"] = "雷达图",
        ["charts.page.radar.description"] = "以辐条上的形状表示系列：每一行命名一根辐条，每个系列沿辐条的值闭合成轮廓，与其他系列对照阅读。",
        ["charts.page.sparks-and-gauges"] = "迷你图与仪表",
        ["charts.page.sparks-and-gauges.description"] = "放在单元格或卡片一角的图表；取一个读数，看负载的迷你图和弧线随之变化。",
        ["charts.code"] = "代码",
        ["charts.copy"] = "复制"
    };

    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Build()
        => new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.Ordinal) { ["en"] = English, ["zh-Hans"] = Chinese };
}
